version: '2'
services:
  mysql:
    build:  ./docker/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=aledruk_uticket
      - MYSQL_PASSWORD=ticketinspector
      - MYSQL_DATABASE=aledruk_ticket
      - MYSQL_ROOT_PASSWORD=ticketinspector
    expose:
      - 3306

  web:
    build: ./docker/apache
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

